services:
  mysqldb:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: lokesh
      MYSQL_DATABASE: hackathondb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    image: sailokeshreddy123/hackathon-frontend:latest
    container_name: springboot
    ports:
      - "2222:2004"
    depends_on:
      - mysqldb
    restart: on-failure

  frontend:
    image: sailokeshreddy123/hackathon-backend:latest
    container_name: react
    ports:
      - "1234:80"
    depends_on:
      - backend
    restart: on-failure

volumes:
  mysql_data: